### ISSUE TITLE
fix actions

### ISSUE THREAD

**Issue by ahdinosaur** [pietgeursen/conway-functional#3]
> wait... your actions are messed up, they should be functions that return action objects (a more clear name for them is "action creator" rather than just "action"). it seems like you're returning state from your actions. as in, your reducers shouldn't be referencing your action creators, but they could still reference conway.js as those are more of helper functions for operating on state than action creators.

**Comment by pietgeursen** [comment]
Waiting on review from Mikey

**Comment by ahdinosaur** [comment]
looks good to me. :)
